function onIRCRecieve(msg,sender,msg_total,param,chan)
         local vont = {
         'dár para um macho',
         'comer comida',
         'comer uma mulher',
         'beber agua',
         'para de fala (xato pra caralho)',
         'ir dormir',
         'estudar',
         'xera a bunda',
         'ir ao banheiro',
         'ser banido',
         'ser ignorado pq é mto xato',
         '(Te interessa)',
         'fazer uma coisa muito divertida',
         'sair do IRC e cata uma mina',
         'sair do IRC e cata um macho',
         'morre',
         'almoçar',
         'beber agua',
         'tomar banho',
         'jogar um jogo',
         'ver pornografia infantil',
         'chupar alguma coisa urgentemente',
         'ronaldo',
         'dar... comida pros pobre',
         'arranjar um emprego',
         'para de usar o bearbot pq faz espa pra krl',
         'Fazer um luabot usando multi-threat e para mock',
         'Dar a bunda',
         'orar',
         'tomar sorvete',
         'andar de patinete',
         'jogar peteca',
         'pega nas bolas',
         'coça o saco',
         'NUM TE INTERESSA N _|_',
         'ligar pra sua mae',
         'se prostituir',
         'para de gasta grana com internet e paga uma put@',
         'xingar',
         'ser gay',
         'ser feliz',
         'xorar',
         'pula do predio',
         'ser emo',
         'fazer um script',
         'molha o cu',
         'dar todos seus valutis',
         'se joga',
         'criar vergonha na cara',
         'peida',
		 'chupar uma rola bem grande preta e cabeluda na frnete de 50 pessoas',
		 'pagar um boquete',
		 'enfier o dedo no cu',
		 'sai do pc',
		 'virar emo',
		 'toma no cu',
		 'sentir um pau entrando no seu cu',
		 'trollar',
		 'ser trollado',
		 'fish ball cat'
         }
		--[[local vont = {
		'shut up',
		'eat something',
		'LOL',
		'drink something',
		'go sleep',
		'stop play with this bot',
		'do nothing',
		'go to shower',
		'cry',
		'play a game',
		'stop smoking',
		'keep trolling some one',
		'die',
		'dance',
		'q',
		'laught',
		'run',
		'cut all their fur',
		'-',
		'yell',
		}]]
         botSendMsg('0,1211<1>157'..sender..'15 quer 7'..vont[math.random(1,#vont)]..'15.0,1211<1>',false,chan)

    return TRUE
end
